version: '3.9'

services:
    node-app:
        build:
            context: ./api
        container_name: nodeserver
        env_file:
            - ./api/.env.example
        ports:
            - '3000:3000'
        networks:
            - nginx-proxy
    nginx:
        build:
            context: ./nginx
        container_name: nginx
        ports:
            - '80:80'
        depends_on:
            - node-app
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external: true
